### PR TITLE
Add espresso

### PR DESCRIPTION
**Pull request by PythonFZ**

### CODE REVIEW

**Comment by SamTov** [comment]
A general point here. If the idea of having H5MD as a standard is to standardize the way in which data is stored, what is the goal behind having wrappers for different simulation engines? In deployment, one would want that the library identifies all groups available to it and returns them regardless of their naming convention as if they are stored under the h5md format it should remain relatively consistent.

**Comment by PythonFZ** [comment]
> What is the goal behind having wrappers for different simulation engines?

Lammps stores the values in `particles/all/` and espresso in `particles/atoms/` so we have to distinguish between those. 

> In deployment, one would want that the library identifies all groups available to it and returns them regardless of their naming convention as if they are stored under the h5md format it should remain relatively consistent.

This can not be accomplished because for autocompletion to work, the structure must be defined and can not be generated dynamically. The idea is, to collect all possible properties and raise a `GroupNotFound` error if a group is not available in the given file.

We could consider adding a `znh5md.H5MD` class that tries to detect if the given file has `particles/all/` or `particles/atoms/`.

**Review by SamTov — APPROVED** [review]
Looks nice, I think in the case where naming conventions are broken it would be worth putting a PR or issue up on the respective repo to say that a violation has occured.

**Comment by SamTov** [comment]
> > What is the goal behind having wrappers for different simulation engines?
> 
> Lammps stores the values in `particles/all/` and espresso in `particles/atoms/` so we have to distinguish between those.
> 
> > In deployment, one would want that the library identifies all groups available to it and returns them regardless of their naming convention as if they are stored under the h5md format it should remain relatively consistent.
> 
> This can not be accomplished because for autocompletion to work, the structure must be defined and can not be generated dynamically. The idea is, to collect all possible properties and raise a `GroupNotFound` error if a group is not available in the given file.
> 
> We could consider adding a `znh5md.H5MD` class that tries to detect if the given file has `particles/all/` or `particles/atoms/`.

Sure it just makes redundant the idea of a standard.

**Pull request merged**
